# 对话文本配置

# 定义所有台词
[lines]
112301200 = "冒险者，你想十分吗？"
112301300 = "原来如此，你想**啊"
112996100 = "什么，你在说什么鬼"
112997100 = "没错，就是这样"
112301400 = "我满足你的愿望"
994154200 = "..."

# 定义对话选项
[line_options]
654789257 = [
    { id = 112996100, condition = "return true"}, 
    { id=112997100,  condition = "return true"}]

# 定义对话流
# 定义对话流
[[dialogs]]
condition = "return true"
id = 666  # 对话流ID
flow = [  # 连续对话流
    { id = 112301200 },  # 独白. 默认说话是NPC自己
    { id = 112301300 },
    { id = 112301400 },
    { speaker = 1, id = 654789257 },
]

# 定义分支
[[dialogs.branches]]
id = 777  # 分支ID
flow = [  # 分支的连续对话流
    { type = "section", id = 444123456 }  # 独白
]
to = 689  # 分支的目标对话流ID

[[dialogs.branches]]
id = 888  # 分支ID
flow = [  # 分支的连续对话流
    { type = "section", id = 555789123 }  # 独白
]
to = 689  # 分支的目标对话流ID

# 定义目标对话流
[[dialogs]]
id = 689  # 目标对话流ID
flow = [  # 连续对话流
    {  id = 112301200 }  # 独白
]