
[[Skills]]
Key = {No="00002", Name="Tap"}
Type = "Phased"

[[Skills.Phases]]
Key = {No="00002", Name="Tap"}
Handlers = ['Mount', 'CollideAttack', 'Scriptable']

Attack={Atk=10.0, Matk=1.0}
Colliders=['W_Sword']

[[Skills.Phases.Mount.Casting.Prefabs]] # 定義爲階段下的預製體子表
Address = 'PF_Frame_001' # 預製體的索引
MountPoint = "W_Sword"
InWorldSpace= false
DestroyDelay=1.0


[[Skills.Phases]]
Key = {No="00002", Name="Tap2"}
Handlers = ['Mount', 'CollideAttack', 'Scriptable']

Attack={Atk=10.0, Matk=1.0}
Colliders=['W_Sword']

[[Skills.Phases.Mount.Casting.Prefabs]] # 定義爲階段下的預製體子表
Address = 'PF_Frame_001' # 預製體的索引
MountPoint = "W_Sword"
InWorldSpace= false
DestroyDelay=1.0