name: Build Project

on:
    push:
        branches:
            - main
            - next
            - feat-github_action
            

jobs:
    build:
        runs-on: windows-latest
        environment: Unity
        steps:
          - name: Checkout project
            uses: actions/checkout@v2

          - name: Setup Unity
            uses: kuler90/setup-unity@v1
            with:
              unity-modules: android
        
          - name: Activate Unity
            uses: kuler90/activate-unity@v1
            with:
              unity-username: ${{ secrets.UNITY_USERNAME }}
              unity-password: ${{ secrets.UNITY_PASSWORD }}
        #      unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
        
          - name: Build Unity
            uses: kuler90/build-unity@v1
            with:
              build-target: Android
              build-path: ./build.apk