name: Build Project

on:
    push:
        branches:
            - main
            - next
            - feat-github_action
            

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Unity

        steps:
          # Check
          - name: Checkout project
            uses: actions/checkout@v4
            with:
              lfs: true

          # Cache
          - name: Cache
            uses: actions/cache@v3
            with:
              path: Library
              key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
              restore-keys: |
                Library-

          # Test
          - name: Run tests
            uses: game-ci/unity-test-runner@v4
            env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            with:
              githubToken: ${{ secrets.GITHUB_TOKEN }}

          # Build
          - name: Build project
            uses: game-ci/unity-builder@v4
            env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            with:
              targetPlatform: WebGL

          # Output
          - uses: actions/upload-artifact@v3
            with:
              name: Build
              path: build